[package]
name = "dll-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "dll_rs"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
cc = "1.2.22"

[dependencies]
ssh2 = {version = "0.9.5"}
